# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6c60d71dadd4ffcd4be404f7dae07c1aa12c65d2e0d9586092ea9152e0a067ebd5bfa852c194aef3d1db113a7e6ea1246f4f78abae45a1b2e0526f006734e74

test:
  secret_key_base: cf95716ef1b29b4086a9ac3bd53bf023572ee8832e989ec6ef99a1e7a6a53bd890e1923385cee4cc0cd35fbf505f67d5ad6cd1b66c86eb63f74d87f7bbe09bbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
